"""empty message

Revision ID: 8088f9cc55ee
Revises: aa2f53ab1e20
Create Date: 2020-11-10 18:14:19.602217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8088f9cc55ee'
down_revision = 'aa2f53ab1e20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("test") as batch_op:
        #batch_op.add_column(Column('foo', Integer)) - used to add a row
        batch_op.drop_column('remove') 
        '''
        Because of with, I don't need to reference table as below
        because with already does that
        '''
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('remove', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
